### ISSUE TITLE
New vulnerability

### ISSUE THREAD

**Issue by M1sIft** [svgpp/svgpp#102]
**Example：**
[id^%000000,sig^%11,src^%000000,time^%16771,execs^%970,op^%flip1,pos^%62.zip](https://github.com/svgpp/svgpp/files/8482620/id.000000.sig.11.src.000000.time.16771.execs.970.op.flip1.pos.62.zip)
**Analyze：**

> In setSize() in svgpp_render.cpp:334, buffer_.resize is 0 because the width attribute in the svg file is set to 0%, and the resulting buffer[0] is 0, which is caused by the execution to agg_pixfmt_rgba.h:1646 null pointer reference

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2135593==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x0000006d1143 bp 0x7ffeb3c89c00 sp 0x7ffeb3c899c0 T0)
==2135593==The signal is caused by a READ memory access.
==2135593==Hint: address points to the zero page.
    #0 0x6d1143 in agg::row_accessor<unsigned char>::width() const /home/misift/fuzzing_svg/svgpp-1.3.0 (copy)/src/demo/render/../../../third_party/agg/include/agg_rendering_buffer.h:73:53
    #1 0x6d1143 in agg::pixfmt_alpha_blend_rgba<agg::blender_rgba<agg::rgba8T<agg::linear>, agg::order_rgba>, agg::row_accessor<unsigned char> >::width() const /home/misift/fuzzing_svg/svgpp-1.3.0 (copy)/src/demo/render/../../../third_party/agg/include/agg_pixfmt_rgba.h:1646:61
    #2 0x6d1143 in main /home/misift/fuzzing_svg/svgpp-1.3.0 (copy)/src/demo/render/svgpp_render.cpp:1709:60
    #3 0x7f2a6f521082 in __libc_start_main /build/glibc-KZwQYS/glibc-2.31/csu/../csu/libc-start.c:308:16
    #4 0x5f9a8d in _start (/home/misift/fuzzing_svg/svgpp-1.3.0 (copy)/src/build/bin/svgpp_agg_render+0x5f9a8d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/misift/fuzzing_svg/svgpp-1.3.0 (copy)/src/demo/render/../../../third_party/agg/include/agg_rendering_buffer.h:73:53 in agg::row_accessor<unsigned char>::width() const
==2135593==ABORTING

```
credit：misift_Zero

**Comment by 001SM** [comment]
tql,dddd
